name: Python unittest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system
      - name: Run unittest
        run: python -m unittest

